name: 'Setup Oracle JET'
description: 'Set up your GitHub Actions workflow with Cordova/Oracle JET environment. Only supports macos & ubuntu at this time.'
author: 'dsileikaevry'
branding:
  color: purple
  icon: code

inputs:
  cordova-version:
    description: Version range or exact version of Cordova to use
    default: '10'
  ojet-version:
    description: Version range or exact version of Oracle JET CI to use
    default: '10.0.0'
  install-java:
    description: Whether to install Java
    default: false
  install-pods:
    description: Whether to install CocoaPods
    default: false

runs:
  using: 'node12'
  main: 'dist/index.js'
