name: "CI"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - master

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    # runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: joschi/setup-jdk@v2 
      with:
        java-version: '8'
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
    - uses: actions/setup-node@v2
      with:
        # Issue: https://stackoverflow.com/a/62514416
        node-version: '12.18.1'
    - run: |  
        npm ci
        npm run all
  test: # make sure the action works on a clean machine without building
    needs: [build]
    runs-on: ubuntu-latest
    # runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: joschi/setup-jdk@v2 
      with:
        java-version: '8'
    - uses: actions/setup-node@v2
      with:
        # Issue: https://stackoverflow.com/a/62514416
        node-version: '12.18.1'
    - name: Use dsileikaevry/setup-ojet
      uses: ./
    - name: Create test Oracle JET application
      run: | 
        ojet create myHybridApp --hybrid --platforms="android,ios" --appid="com.oracle.myApp" --appname="My App" --template=navdrawer
        cd myHybridApp  
        ojet build android
